# Generated by Django 6.0.6 on 2026-07-02 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Booking Conflict',
                'verbose_name_plural': 'Booking Conflicts',
                'db_table': 'booking_conflicts',
            },
        ),
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('ON_THE_WAY', 'Provider On the Way'), ('ARRIVED', 'Provider Arrived'), ('IN_PROGRESS', 'Service In Progress'), ('COMPLETED', 'Completed'), ('CANCELLELED_BY_CUSTOMER', 'Canceled by Customer'), ('CANCELLELED_BY_PROVIDER', 'Canceled by Provider'), ('CANCELLELED_BY_ADMIN', 'Canceled by Admin'), ('REFUNDED', 'Refunded')], max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Booking Status History',
                'verbose_name_plural': 'Booking Status Histories',
                'db_table': 'booking_status_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('service_date', models.DateField()),
                ('service_time', models.TimeField()),
                ('service_duration_minutes', models.PositiveIntegerField(default=60)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('provider_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('ON_THE_WAY', 'Provider On the Way'), ('ARRIVED', 'Provider Arrived'), ('IN_PROGRESS', 'Service In Progress'), ('COMPLETED', 'Completed'), ('CANCELLELED_BY_CUSTOMER', 'Canceled by Customer'), ('CANCELLELED_BY_PROVIDER', 'Canceled by Provider'), ('CANCELLELED_BY_ADMIN', 'Canceled by Admin'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=30)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], default='PENDING', max_length=30)),
                ('payment_method', models.CharField(blank=True, choices=[('UPI', 'UPI'), ('CARD', 'Credit/Debit Card'), ('NET_BANKING', 'Net Banking'), ('WALLET', 'Wallet'), ('CASH', 'Cash'), ('RAZORPAY', 'Razorpay'), ('STRIPE', 'Stripe')], max_length=20, null=True)),
                ('is_rated', models.BooleanField(default=False)),
                ('is_urgent', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
