# Generated by Django 6.0.6 on 2026-07-02 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('payments', '0001_initial'),
        ('services', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.coupon'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='services.service'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.address'),
        ),
        migrations.AddField(
            model_name='bookingconflict',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingconflict',
            name='conflicting_booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicted_by', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingstatushistory',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_id'], name='bookings_booking_dcd799_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer', 'status', 'service_date'], name='bookings_custome_8b008e_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['provider', 'status', 'service_date'], name='bookings_provide_f8ac7c_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['service', 'service_date', 'service_time'], name='bookings_service_a480ce_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'payment_status'], name='bookings_status_1b5f35_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingconflict',
            index=models.Index(fields=['booking', 'resolved'], name='booking_con_booking_40ad0c_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingconflict',
            index=models.Index(fields=['conflicting_booking', 'resolved'], name='booking_con_conflic_1c468f_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingstatushistory',
            index=models.Index(fields=['booking', 'created_at'], name='booking_sta_booking_96150c_idx'),
        ),
    ]
