# Generated by Django 6.0.6 on 2026-07-02 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('business_description', models.TextField(blank=True, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('service_radius', models.PositiveIntegerField(default=10, help_text='Service radius in km')),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('team_size', models.PositiveIntegerField(default=1)),
                ('minimum_charge', models.DecimalField(decimal_places=2, default=99.0, max_digits=10)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('total_jobs', models.PositiveIntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('languages', models.JSONField(default=list, help_text='List of languages spoken')),
                ('bank_account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_ifsc_code', models.CharField(blank=True, max_length=11, null=True)),
                ('bank_account_holder', models.CharField(blank=True, max_length=100, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'db_table': 'providers',
            },
        ),
        migrations.CreateModel(
            name='ProviderAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='providers.provider')),
            ],
            options={
                'verbose_name': 'Provider Availability',
                'verbose_name_plural': 'Provider Availabilities',
                'db_table': 'provider_availability',
            },
        ),
        migrations.CreateModel(
            name='ProviderBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='providers.provider')),
            ],
            options={
                'verbose_name': 'Provider Break',
                'verbose_name_plural': 'Provider Breaks',
                'db_table': 'provider_breaks',
            },
        ),
        migrations.CreateModel(
            name='ProviderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('AADHAR', 'Aadhar Card'), ('PAN', 'PAN Card'), ('DRIVING_LICENSE', 'Driving License'), ('VOTER_ID', 'Voter ID'), ('PASSPORT', 'Passport'), ('BANK_PASSBOOK', 'Bank Passbook'), ('BUSINESS_LICENSE', 'Business License'), ('OTHER', 'Other')], max_length=30)),
                ('document_number', models.CharField(max_length=50)),
                ('document_file', models.FileField(upload_to='providers/documents/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='providers.provider')),
            ],
            options={
                'verbose_name': 'Provider Document',
                'verbose_name_plural': 'Provider Documents',
                'db_table': 'provider_documents',
            },
        ),
        migrations.CreateModel(
            name='ProviderGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='providers/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='providers.provider')),
            ],
            options={
                'verbose_name': 'Provider Gallery',
                'verbose_name_plural': 'Provider Galleries',
                'db_table': 'provider_gallery',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['verification_status', 'is_available'], name='providers_verific_866686_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['average_rating', 'total_jobs'], name='providers_average_95a298_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['is_featured', 'average_rating'], name='providers_is_feat_4419a6_idx'),
        ),
        migrations.AddIndex(
            model_name='provideravailability',
            index=models.Index(fields=['provider', 'day_of_week', 'is_available'], name='provider_av_provide_073118_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='provideravailability',
            unique_together={('provider', 'day_of_week')},
        ),
        migrations.AddIndex(
            model_name='providerbreak',
            index=models.Index(fields=['provider', 'date'], name='provider_br_provide_45ea20_idx'),
        ),
        migrations.AddIndex(
            model_name='providerdocument',
            index=models.Index(fields=['provider', 'document_type'], name='provider_do_provide_29d442_idx'),
        ),
    ]
