# Generated by Django 6.0.6 on 2026-07-02 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('new_users', models.PositiveIntegerField(default=0)),
                ('total_providers', models.PositiveIntegerField(default=0)),
                ('new_providers', models.PositiveIntegerField(default=0)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('completed_bookings', models.PositiveIntegerField(default=0)),
                ('canceled_bookings', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('platform_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('provider_payouts', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_services', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Stats',
                'verbose_name_plural': 'Daily Stats',
                'db_table': 'daily_stats',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='daily_stats_date_c5e813_idx')],
            },
        ),
        migrations.CreateModel(
            name='CategoryStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('bookings_count', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='categories.category')),
            ],
            options={
                'verbose_name': 'Category Stats',
                'verbose_name_plural': 'Category Stats',
                'db_table': 'category_stats',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['category', 'date'], name='category_st_categor_74d436_idx')],
                'unique_together': {('category', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ProviderStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('bookings_received', models.PositiveIntegerField(default=0)),
                ('bookings_completed', models.PositiveIntegerField(default=0)),
                ('bookings_canceled', models.PositiveIntegerField(default=0)),
                ('earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provider Stats',
                'verbose_name_plural': 'Provider Stats',
                'db_table': 'provider_stats',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['provider', 'date'], name='provider_st_provide_58fb8f_idx')],
                'unique_together': {('provider', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SearchAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=200)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clicked_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search Analytics',
                'verbose_name_plural': 'Search Analytics',
                'db_table': 'search_analytics',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['query', 'created_at'], name='search_anal_query_2667a1_idx'), models.Index(fields=['created_at'], name='search_anal_created_b2167e_idx')],
            },
        ),
    ]
