# Generated by Django 6.0.6 on 2026-07-02 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('payments', '0001_initial'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('WELCOME', 'Welcome Email'), ('OTP', 'OTP Email'), ('BOOKING_CONFIRMATION', 'Booking Confirmation'), ('BOOKING_REMINDER', 'Booking Reminder'), ('PAYMENT_RECEIPT', 'Payment Receipt'), ('REVIEW_REQUEST', 'Review Request'), ('PROVIDER_APPROVED', 'Provider Approved'), ('PASSWORD_RESET', 'Password Reset')], max_length=30, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('body_html', models.TextField()),
                ('body_text', models.TextField(blank=True, null=True)),
                ('variables', models.JSONField(default=list, help_text='Available variables')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'db_table': 'email_templates',
            },
        ),
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('OTP', 'OTP SMS'), ('BOOKING_CONFIRMATION', 'Booking Confirmation'), ('BOOKING_REMINDER', 'Booking Reminder'), ('PAYMENT_RECEIPT', 'Payment Receipt'), ('PROVIDER_APPROVED', 'Provider Approved')], max_length=30, unique=True)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS Template',
                'verbose_name_plural': 'SMS Templates',
                'db_table': 'sms_templates',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('BOOKING_REQUEST', 'Booking Request'), ('BOOKING_ACCEPTED', 'Booking Accepted'), ('BOOKING_REJECTED', 'Booking Rejected'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('BOOKING_COMPLETED', 'Booking Completed'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_FAILED', 'Payment Failed'), ('REVIEW_RECEIVED', 'Review Received'), ('PROVIDER_VERIFIED', 'Provider Verified'), ('PROVIDER_SUSPENDED', 'Provider Suspended'), ('WITHDRAWAL_APPROVED', 'Withdrawal Approved'), ('WITHDRAWAL_REJECTED', 'Withdrawal Rejected'), ('SYSTEM', 'System Notification'), ('PROMOTION', 'Promotion')], max_length=30)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-App'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push Notification')], default='IN_APP', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(default=dict, help_text='Additional data')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.payment')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.review')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='notificatio_recipie_06c470_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx')],
            },
        ),
        migrations.CreateModel(
            name='PushNotificationDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web')], max_length=10)),
                ('device_token', models.CharField(db_index=True, max_length=255)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push Notification Device',
                'verbose_name_plural': 'Push Notification Devices',
                'db_table': 'push_notification_devices',
                'indexes': [models.Index(fields=['device_token', 'is_active'], name='push_notifi_device__9272aa_idx')],
                'unique_together': {('user', 'device_token')},
            },
        ),
    ]
